### PR TITLE
Fix the in query building to handle one or empty special cases

### PR DESCRIPTION
**Pull request by gzsombor**

### CODE REVIEW

**Comment by gzsombor** [comment]
What do you think? Does it make sense?

**Comment by npgall** [comment]
Hi Zsombor yes this is a good idea, it makes sense.
I have merged your commit, many thanks!

**Comment by gzsombor** [comment]
Welcome !

**Comment by npgall** [comment]
Just to let you know I have release CQEngine 2.1.1 which includes your pull request, and it should sync to Maven Central in the next ~2 hours. Many thanks!

**Comment by gzsombor** [comment]
Great, thanks!

**Pull request merged**
