### PR TITLE
Auto-generate attributes from the Getters in a given POJO class

### PR DESCRIPTION
**Pull request by nivs**
New method `createAttributesForGetters()` in `AttributeBytecodeGenerator` (based on the original `createAttributes`) for automatically generating attributes for Getters - methods with specific prefixes (get, is, has) which are non-private and parameterless,  declared directly in the POJO class or inherited.

### CODE REVIEW

**Comment by npgall** [comment]
Many thanks nivs, this looks like a good addition!
Merged!
It will be included in the next release, ETA ~in the next week.

**Comment by npgall** [comment]
It looks like this PR didn't include tests, so it has reduced the test coverage.
Any chance you could submit an additional PR to add tests for it?
If not, I'm afraid I will have to remove this feature again, as we require test coverage for all new features.

**Comment by nivs** [comment]
Sure thing, I'll write some tests.

**Comment by npgall** [comment]
Hi nivs I've had to back out these changes temporarily, as I want to make a release soon and can't include this feature until we have unit tests for it. Let me know when you get a chance to add tests, and then we can merge it in again. Thanks!

**Comment by npgall** [comment]
FYI this feature is now included in release 2.12.2. 
The implementation is a bit different to the earlier approach as I wanted to add support in AttributeSourceGenerator too. Both now provide the same feature.

**Pull request merged**
