### PR TITLE
Added OSGi headers to MANIFEST.MF

### PR DESCRIPTION
**Pull request by efernandezleon**
Add maven-bundle-plugin in order to add OSGi headers in the MANIFEST.MF file. By default, when the JAR is created these headers are included in MANIFEST.MF for using JAR as single OSGi bundle.

By other hand, a profile is created in order to build an all-in-one bundle where every external dependency is in the JAR and referenced with the Bundle-Classpath header in the MANIFEST. To package with this profile just use the command `mvn install -P all-in-one-osgi`

### CODE REVIEW

**Comment by npgall** [comment]
Hi Eduardo,

Thanks again for the PR. I'm preparing for the next release, so I'd like to merge this soon.

You mentioned in issue #71 that _"CQEngine has dependencies that they are not OSGIfied , so for us, is better to include every third-party dependency inside of the JAR using OSGi techniques"_. And that's why you added the "all-in-one-osgi" profile in the pom.xml as well, right?

IntelliJ is telling me that only one of CQEngine's dependencies is not OSGIfied and it's the "concurrent-trees" 2.4.0 library which I also own. I recently OSGIfied that one in mainline actually - I just haven't released it yet.

So if I release an OSGIfied version of the "concurrent-trees" library and I upgrade CQEngine to use that version, then all of CQEngine's dependencies will be OSGI compatible, right?

So at that point does it mean we can remove the "all-in-one-osgi" profile from the pom.xml in this pull request? I'd prefer not to have to have a separate build profile just for OSGi support.

Would that work for you?

Thanks,
Niall

**Comment by efernandezleon** [comment]
Hi Niall,

Maybe, with all dependencies with OSGi headers this profile has no sense. Let me check the build with update dependencies.

Regards,
Eduardo F.

**Comment by efernandezleon** [comment]
Hi Niall,

Just check it. As you said, if "concurrent-trees" provides OSGi headers, then the proposed profile has no sense. 

Thank you anyway.

Regards,
Eduardo F.

**Comment by npgall** [comment]
Hi Eduardo,

No problem. I will merge the OSGi support you added in the next day or two, and I will just remove the profile. Many thanks!

**Pull request merged**
