### PR TITLE
#253 support for longest prefix queries

### PR DESCRIPTION
**Pull request by glockhart**
Implementation for https://github.com/npgall/cqengine/issues/253

The change to the FallbackIndex should probably get the most scrutiny as this is a change in behaviour that may not be appreciated.

### CODE REVIEW

**Comment by glockhart** [comment]
@npgall any comments or concerns with this PR that I can address?

**Comment by glockhart** [comment]
@npgall Thanks for the feedback.
I've addressed your first concern and updated the PR with my changes.
I'll look into seeing if I have time to implement your request for the second Query type

**Comment by glockhart** [comment]
@npgall That second query type didn't take too long, so I've added it to the PR.

Let me know what you think when you get a chance.

Glen

**Comment by npgall** [comment]
That sounds great I will take a look in the next few days, many thanks!

**Comment by npgall** [comment]
This is now merged.

I will be working on CQEngine today and I'm planning to make a new release in the next few days which will include this.

Many thanks Glen for the contribution!

**Pull request merged**
